#!/bin/bash

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files -o --exclude-standard | \
    ctags --c++-kinds=+p --fields=+nliaS --extras=+q --tag-relative=yes -L - -f "$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
